package com.krzz.calculadora;

import com.formdev.flatlaf.*;
import com.formdev.flatlaf.themes.*;
import java.awt.Color;
import java.awt.EventQueue;
import javax.swing.UIManager;

/**
 * @author Krzz.
 */
public class jFrameCalculator1 extends javax.swing.JFrame {

    private boolean igual, inicio = true, op1, op2;
    private double a, b, c, memoria = 0, resultado, valor1, valor2, cos, acos, sin, asin, tan, atan;
    private String cadena, funciones, tipoOperaciones, pruebaPro;

    /**
     * Creates new form frame
     */
    public jFrameCalculator1() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        jBtnSqrt.setText("²√x");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuSin = new javax.swing.JMenuItem();
        jMenuCos = new javax.swing.JMenuItem();
        jMenuTan = new javax.swing.JMenuItem();
        jMenuSin2 = new javax.swing.JMenuItem();
        jMenuCos2 = new javax.swing.JMenuItem();
        jMenuTan2 = new javax.swing.JMenuItem();
        Trigonometria = new javax.swing.ButtonGroup();
        Results = new javax.swing.JPanel();
        jTxtSecundario = new javax.swing.JTextField();
        jTxtPrincipal = new javax.swing.JTextField();
        jLblTrigonometria = new javax.swing.JLabel();
        ToggleTheme = new javax.swing.JToggleButton();
        Buttons = new javax.swing.JPanel();
        jBtnFactorial = new javax.swing.JButton();
        jBtn19 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jBtnLn2 = new javax.swing.JButton();
        jBtnDividedBy1 = new javax.swing.JButton();
        jBtnPi = new javax.swing.JButton();
        jBtnSqrt = new javax.swing.JButton();
        jBtnRoundBracket1 = new javax.swing.JButton();
        jBtnRoundBracket2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jBtn17 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnAC = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jBtnLn1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnMulti = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnResta = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnSuma = new javax.swing.JButton();
        jBtnEqual = new javax.swing.JButton();
        ToggleFuntions = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRdbSexages = new javax.swing.JRadioButton();
        jRdbRadianes = new javax.swing.JRadioButton();

        jMenuSin.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuSin.setLabel("sin(\n");
        jMenuSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSinActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuSin);

        jMenuCos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuCos.setLabel("cos(");
        jMenuCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuCos);

        jMenuTan.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuTan.setLabel("tan(");
        jMenuTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTanActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuTan);

        jMenuSin2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuSin2.setLabel("sin-¹(");
        jMenuSin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSin2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuSin2);

        jMenuCos2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuCos2.setLabel("cos-¹(");
        jMenuCos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCos2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuCos2);

        jMenuTan2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jMenuTan2.setLabel("tan-¹(");
        jMenuTan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTan2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuTan2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jTxtSecundario.setEditable(false);
        jTxtSecundario.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jTxtSecundario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtSecundario.setBorder(null);
        jTxtSecundario.setFocusable(false);

        jTxtPrincipal.setEditable(false);
        jTxtPrincipal.setFont(new java.awt.Font("Inter", 1, 40)); // NOI18N
        jTxtPrincipal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtPrincipal.setBorder(null);
        jTxtPrincipal.setFocusable(false);

        javax.swing.GroupLayout ResultsLayout = new javax.swing.GroupLayout(Results);
        Results.setLayout(ResultsLayout);
        ResultsLayout.setHorizontalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtSecundario)
                    .addComponent(jTxtPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ResultsLayout.setVerticalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxtSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblTrigonometria.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLblTrigonometria.setText("Trigonometría ▼");
        jLblTrigonometria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblTrigonometriaMouseReleased(evt);
            }
        });

        ToggleTheme.setBackground(java.awt.Color.white);
        ToggleTheme.setForeground(java.awt.Color.white);
        ToggleTheme.setSelected(true);
        ToggleTheme.setFocusPainted(false);
        ToggleTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleThemeActionPerformed(evt);
            }
        });

        jBtnFactorial.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnFactorial.setText("n!");
        jBtnFactorial.setFocusPainted(false);
        jBtnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFactorialActionPerformed(evt);
            }
        });

        jBtn19.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtn19.setText("EXP");
        jBtn19.setFocusPainted(false);
        jBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn19ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton8.setText("e");
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jBtnLn2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnLn2.setText("10ˣ");
        jBtnLn2.setFocusPainted(false);
        jBtnLn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLn2ActionPerformed(evt);
            }
        });

        jBtnDividedBy1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnDividedBy1.setText("÷");
        jBtnDividedBy1.setFocusPainted(false);
        jBtnDividedBy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDividedBy1ActionPerformed(evt);
            }
        });

        jBtnPi.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnPi.setText("π");
        jBtnPi.setFocusPainted(false);
        jBtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiActionPerformed(evt);
            }
        });

        jBtnSqrt.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnSqrt.setText("²√x ");
        jBtnSqrt.setFocusPainted(false);
        jBtnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSqrtActionPerformed(evt);
            }
        });

        jBtnRoundBracket1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnRoundBracket1.setText("(");
        jBtnRoundBracket1.setFocusPainted(false);
        jBtnRoundBracket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRoundBracket1ActionPerformed(evt);
            }
        });

        jBtnRoundBracket2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnRoundBracket2.setText(")");
        jBtnRoundBracket2.setFocusPainted(false);
        jBtnRoundBracket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRoundBracket2ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton7.setText("xʸ");
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jBtn17.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtn17.setText("%");
        jBtn17.setFocusPainted(false);
        jBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn17ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton12.setText("x²");
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn7.setText("7");
        jBtn7.setFocusPainted(false);
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn8.setText("8");
        jBtn8.setFocusPainted(false);
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn4.setText("4");
        jBtn4.setFocusPainted(false);
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn5.setText("5");
        jBtn5.setFocusPainted(false);
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn1.setText("1");
        jBtn1.setFocusPainted(false);
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn2.setText("2");
        jBtn2.setFocusPainted(false);
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.setFocusPainted(false);
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtnDot.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnDot.setText(".");
        jBtnDot.setFocusPainted(false);
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });

        jBtnDel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtnDel.setText("DEL");
        jBtnDel.setFocusPainted(false);
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });

        jBtnAC.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtnAC.setText("AC");
        jBtnAC.setFocusPainted(false);
        jBtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnACActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton22.setText("log");
        jButton22.setFocusPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jBtnLn1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnLn1.setText("ln");
        jBtnLn1.setFocusPainted(false);

        jButton13.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton13.setText("x-¹");
        jButton13.setFocusPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jBtnDiv.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnDiv.setText("÷");
        jBtnDiv.setFocusPainted(false);
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn9.setText("9");
        jBtn9.setFocusPainted(false);
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnMulti.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnMulti.setText("×");
        jBtnMulti.setFocusPainted(false);
        jBtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn6.setText("6");
        jBtn6.setFocusPainted(false);
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtnResta.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnResta.setText("-");
        jBtnResta.setFocusPainted(false);
        jBtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestaActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtn3.setText("3");
        jBtn3.setFocusPainted(false);
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnSuma.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jBtnSuma.setText("+");
        jBtnSuma.setFocusPainted(false);
        jBtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumaActionPerformed(evt);
            }
        });

        jBtnEqual.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jBtnEqual.setText("=");
        jBtnEqual.setFocusPainted(false);
        jBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualActionPerformed(evt);
            }
        });

        ToggleFuntions.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        ToggleFuntions.setText("⇄");
        ToggleFuntions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleFuntionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(jBtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(jBtnDividedBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(jBtnLn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(jBtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleFuntions, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ButtonsLayout.createSequentialGroup()
                                .addComponent(jBtnRoundBracket1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRoundBracket2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ButtonsLayout.createSequentialGroup()
                                .addComponent(jBtnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnLn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnRoundBracket1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnRoundBracket2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ToggleFuntions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDividedBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("jLabel3");

        Trigonometria.add(jRdbSexages);
        jRdbSexages.setSelected(true);
        jRdbSexages.setText("Sexages");

        Trigonometria.add(jRdbRadianes);
        jRdbRadianes.setText("Radianes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTrigonometria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRdbSexages)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRdbRadianes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ToggleTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(Results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblTrigonometria, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(jRdbSexages)
                        .addComponent(jRdbRadianes))
                    .addComponent(ToggleTheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToggleThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleThemeActionPerformed
        // Create a new event for theme switching (Dark | White)
        EventQueue.invokeLater(() -> {
            if (ToggleTheme.isSelected()) {
                // If the ToggleButton is selected we put the Dark Theme
                FlatMacDarkLaf.setup();
                FlatLaf.updateUI();
                ToggleTheme.setBackground(Color.white);
            } else {
                // If the ToggleButton isn't selected we put the White Theme
                FlatMacLightLaf.setup();
                FlatLaf.updateUI();
                ToggleTheme.setBackground(Color.black);
            }
        });
    }//GEN-LAST:event_ToggleThemeActionPerformed

    // Numbers
    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("1");
            inicio = false;
            addNumber("1");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "1");
            addNumber("1");
        }
        
        //jBtnEqual.doClick();
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("2");
            inicio = false;
            addNumber("2");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "2");
            addNumber("2");
        }
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("3");
            inicio = false;
            addNumber("3");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "3");
            addNumber("3");
        }
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("4");
            inicio = false;
            addNumber("4");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "4");
            addNumber("4");
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("5");
            inicio = false;
            addNumber("5");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "5");
            addNumber("5");
        }
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("6");
            inicio = false;
            addNumber("6");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "6");
            addNumber("6");
        }
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("7");
            inicio = false;
            addNumber("7");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "7");
            addNumber("7");
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("8");
            inicio = false;
            addNumber("8");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "8");
            addNumber("8");
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("9");
            inicio = false;
            addNumber("9");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "9");
            addNumber("9");
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        if (inicio == true) {
            jTxtPrincipal.setText("");
            jTxtPrincipal.setText("0");
            inicio = false;
            addNumber("0");
        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + "0");
            addNumber("0");
        }
    }//GEN-LAST:event_jBtn0ActionPerformed

    // Dot
    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
        if (jTxtPrincipal.getText().contains(".")) {

        } else {
            jTxtPrincipal.setText(jTxtPrincipal.getText() + ".");
            addNumber(".");
            inicio = false;
        }
    }//GEN-LAST:event_jBtnDotActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Operaciones Basicas"> 
    
    /*
        Cada boton establece la variable de igual e inicio en true para que no haya
        errores al ejecutar el codigo, despues comprueba si op1 es true para saber
        si puede colocar el operador, si esta variable no es true entonces indica que
        op2 si lo es y ahi si colocará el operador.
        
        Por ultimo, ejecuta el codigo referente a la funcion seleccionada al dar
        igual.
    */
    
    private void jBtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumaActionPerformed
        igual = true;
        inicio = true;

        if (op1 = true) { // Si op1 es true, coloca el operador
            valor1 = Double.parseDouble(jTxtPrincipal.getText());
            jTxtSecundario.setText("");
            jTxtSecundario.setText(jTxtPrincipal.getText() + " + ");
            op1 = false;
        } else {
            if (op2 = true) {// Si op2 es true, coloca el operador
                valor2 = Double.parseDouble(jTxtPrincipal.getText());
                jTxtSecundario.setText(jTxtPrincipal.getText() + " + ");
                op2 = false;
            } else { // Si ninguna es true coloca el operador y resuelve.
                jTxtSecundario.setText(jTxtPrincipal.getText() + " + ");
                Operaciones(resultado, valor2);
            }
        }
        
        tipoOperaciones = "+"; // Asigna el tipo de operacion a realizar
    }//GEN-LAST:event_jBtnSumaActionPerformed

    private void jBtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestaActionPerformed
        igual = true;
        inicio = true;

        if (op1 = true) { // Si op1 es true, coloca el operador
            valor1 = Double.parseDouble(jTxtPrincipal.getText());
            jTxtSecundario.setText("");
            jTxtSecundario.setText(jTxtPrincipal.getText() + " - ");
            op1 = false;
        } else {
            if (op2 = true) { // Si op2 es true, coloca el operador
                valor2 = Double.parseDouble(jTxtPrincipal.getText());
                jTxtSecundario.setText(jTxtPrincipal.getText() + " - ");
                op2 = false;
            } else { // Si ninguna es true coloca el operador y resuelve.
                jTxtSecundario.setText(jTxtPrincipal.getText() + " - ");
                Operaciones(resultado, valor2);
            }
        }
        
        tipoOperaciones = "-"; // Asigna el tipo de operacion a realizar
    }//GEN-LAST:event_jBtnRestaActionPerformed

    private void jBtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiActionPerformed
        igual = true;
        inicio = true;

        if (op1 = true) { // Si op1 es true, coloca el operador
            valor1 = Double.parseDouble(jTxtPrincipal.getText());
            jTxtSecundario.setText("");
            jTxtSecundario.setText(jTxtPrincipal.getText() + " × ");
            op1 = false;
        } else {
            if (op2 = true) { // Si op2 es true, coloca el operador
                valor2 = Double.parseDouble(jTxtPrincipal.getText());
                jTxtSecundario.setText(jTxtPrincipal.getText() + " × ");
                op2 = false;
            } else { // Si ninguna es true coloca el operador y resuelve.
                jTxtSecundario.setText(jTxtPrincipal.getText() + " × ");
                Operaciones(resultado, valor2);
            }
        }
        
        tipoOperaciones = "×"; // Asigna el tipo de operacion a realizar
    }//GEN-LAST:event_jBtnMultiActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        igual = true;
        inicio = true;

        if (op1 = true) { // Si op1 es true, coloca el operador
            valor1 = Double.parseDouble(jTxtPrincipal.getText());
            jTxtSecundario.setText("");
            jTxtSecundario.setText(jTxtPrincipal.getText() + " ÷ ");
            op1 = false;
        } else {
            if (op2 = true) { // Si op2 es true, coloca el operador
                valor2 = Double.parseDouble(jTxtPrincipal.getText());
                jTxtSecundario.setText(jTxtPrincipal.getText() + " ÷ ");
                op2 = false;
            } else { // Si ninguna es true coloca el operador y resuelve.
                jTxtSecundario.setText(jTxtPrincipal.getText() + " ÷ ");
                Operaciones(resultado, valor2);
            }
        }
        
        tipoOperaciones = "÷"; // Asigna el tipo de operacion a realizar
    }//GEN-LAST:event_jBtnDivActionPerformed

    /*
        Aqui en esta clase ejecutamos las operaciones dependiendo de la que hayamos
        presionado en el boton, todo mediante un switch case.
    */
    
    private void Operaciones(double valor1, double valor2) {
        switch (tipoOperaciones) { // En caaso de:
            case "+" -> { // Si es una suma, nos dará el resultado de la suma
                resultado = valor1 + valor2;
                jTxtPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(jTxtPrincipal.getText());
            }
            case "-" -> { // Si es una resta, nos dará el resultado de la resta
                resultado = valor1 - valor2;
                jTxtPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(jTxtPrincipal.getText());
            }
            case "×" -> { // Si es una multiplicacion, nos dará el resultado de la multiplicacion
                resultado = valor1 * valor2;
                jTxtPrincipal.setText(resultado + "");
                valor1 = Double.parseDouble(jTxtPrincipal.getText());
            }
            case "÷" -> { // Si es una division, nos dará el resultado de la division
                if (valor2 == 0) {
                    jTxtPrincipal.setText("Error");
                } else {
                    resultado = valor1 / valor2;
                    jTxtPrincipal.setText(resultado + "");
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                }
            }
            case "potencia" -> { // Si es una potencia, nos dará el resultado de la potencia
                resultado = Math.pow(valor1, valor2);
                jTxtPrincipal.setText(resultado + "");
            }
        }
    }
    
    // El boton igual nos sirve para poder obtener el resultado en caso de que no
    // nos lo de automaticamente.
    private void jBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualActionPerformed
        inicio = true;
        op1 = true;

        if (igual == true) {
            if (tipoOperaciones == null) { 
                // Si no hay ninguna operacion seleccionada, no ejecuta nada
            } else { // pero si la hay, ejecuta el codigo.
                valor2 = Double.parseDouble(jTxtPrincipal.getText());
                jTxtSecundario.setText(jTxtSecundario.getText() + jTxtPrincipal.getText());
                Operaciones(valor1, valor2);
                igual = false;
            }
        } else {
            jTxtSecundario.setText("");
            Operaciones(valor1, valor2); // envia el valor de las operaciones a realizar.
        }
    }//GEN-LAST:event_jBtnEqualActionPerformed
    //</editor-fold>
    
    private void jBtnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFactorialActionPerformed
        a = 1;
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText("fact(" + valor1 + ")");
        for (b = 1; b <= valor1; b++) {
            a = a * b;
        }
        jTxtPrincipal.setText(a + "");
    }//GEN-LAST:event_jBtnFactorialActionPerformed

    private void jBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn19ActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtPrincipal.setText(Math.exp(valor1) + "");
    }//GEN-LAST:event_jBtn19ActionPerformed

    private void jLblTrigonometriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblTrigonometriaMouseReleased
        jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jLblTrigonometriaMouseReleased

    private void jBtnDividedBy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDividedBy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDividedBy1ActionPerformed

    // Boton que devuelve el valor de la raiz, ya sea normal o cubica
    private void jBtnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSqrtActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        
        /*
            Comparamos el texto que está en nuestro boton, esto para poder
            ejecutar una u otra funcion. Si el texto es el de la raiz normal
            ejecuta su codigo, pero si es el de la raiz cubica ejecuta el de la
            raiz cubica.
        */
        if (jBtnSqrt.getText() == "²√x") { // Raiz normal
            if (valor1 >= 0) {
                jTxtSecundario.setText("sqrt(" + valor1 + ")");
                jTxtPrincipal.setText(Math.sqrt(valor1) + "");
            }
        } else if (jBtnSqrt.getText() == "³√x") { // Raiz cubica
            a = 1;
            b = 3;
            c = a / b;
            jTxtSecundario.setText("cuberoot(" + valor1 + ")");
            jTxtPrincipal.setText(Math.pow(valor1, c) + "");
        } else { // En caso de que ninguna de las dos sea validas, arroja error
            jTxtPrincipal.setText("Error");
        }
    }//GEN-LAST:event_jBtnSqrtActionPerformed
    
    private void jBtnRoundBracket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRoundBracket1ActionPerformed
        addNumber("(");
    }//GEN-LAST:event_jBtnRoundBracket1ActionPerformed

    private void jBtnRoundBracket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRoundBracket2ActionPerformed
        addNumber(")");
    }//GEN-LAST:event_jBtnRoundBracket2ActionPerformed

    private void jBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn17ActionPerformed
        valor2 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText(jTxtSecundario.getText() + jTxtPrincipal.getText());
        jTxtPrincipal.setText((valor1 * valor2)/100 + "");
        igual = true;
    }//GEN-LAST:event_jBtn17ActionPerformed

    private void jBtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnACActionPerformed
        jTxtPrincipal.setText("0");
        jTxtSecundario.setText("");
        inicio = true;
        funciones = "";
        op1 = true;
        op2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
    }//GEN-LAST:event_jBtnACActionPerformed

    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        if (jTxtPrincipal.getText().length() > 0) {
            jTxtPrincipal.setText(jTxtPrincipal.getText().substring(0, jTxtPrincipal.getText().length() - 1));
            if (jTxtPrincipal.getText().length() == 0) {
               jTxtPrincipal.setText("0");
               inicio = true;
            }
        }
    }//GEN-LAST:event_jBtnDelActionPerformed

    // Boton que devuelve el valor de PI
    private void jBtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiActionPerformed
        jTxtSecundario.setText("PI ");
        jTxtPrincipal.setText(Math.PI + " ");
    }//GEN-LAST:event_jBtnPiActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText(valor1 + "^-1");
        jTxtPrincipal.setText(Math.pow(valor1, -1) + "");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        inicio = true;
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText(valor1 + "^");
        tipoOperaciones = "potencia";
        op1 = false;
        igual = true;
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTxtSecundario.setText("E ");
        jTxtPrincipal.setText(Math.E + "");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ToggleFuntionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleFuntionsActionPerformed
        if (ToggleFuntions.isSelected()) {
                // If the ToggleFunctions is selected we change some functions
                jBtnSqrt.setText("³√x");
            } else {
                // If the ToggleButton isn't selected we put the original functions
                jBtnSqrt.setText("²√x");
            }
    }//GEN-LAST:event_ToggleFuntionsActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText("sqr(" + valor1 + ")");
        jTxtPrincipal.setText(Math.pow(valor1, 2) + "");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jBtnLn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLn2ActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText("powten(" + valor1 + ")");
        jTxtPrincipal.setText(Math.pow(10, valor1) + "");
    }//GEN-LAST:event_jBtnLn2ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        valor1 = Double.parseDouble(jTxtPrincipal.getText());
        jTxtSecundario.setText("log(" + valor1 + ")");
        jTxtPrincipal.setText(Math.log(valor1) + "");
    }//GEN-LAST:event_jButton22ActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Trigonometria">
    
    /*
        Apartado de las funciones de trigonometria, aqui se le asigna a cada
        boton que funcion es la que ejecutaran.
        Primero en la variable funciones se asigna que funcion se está por ejecutar
        para que acontinuacion al ejecutar la clase de trigonometria el programa
        sepa que funcion debe ejecutar.
    */
    
    // Boton que devuelve el valor del seno
    private void jMenuSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSinActionPerformed
        funciones = "sin";
        Trigonometria();
    }//GEN-LAST:event_jMenuSinActionPerformed

    // Boton que devuelve el valor del coseno
    private void jMenuCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCosActionPerformed
        funciones = "cos";
        Trigonometria();
    }//GEN-LAST:event_jMenuCosActionPerformed

    // Boton que devuelve el valor de la tangente
    private void jMenuTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTanActionPerformed
        funciones = "tan";
        Trigonometria();
    }//GEN-LAST:event_jMenuTanActionPerformed

    // Boton que devuelve el valor del seno inverso
    private void jMenuSin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSin2ActionPerformed
        funciones = "asin";
        Trigonometria();
    }//GEN-LAST:event_jMenuSin2ActionPerformed

    // Boton que devuelve el valor del coseno inverso
    private void jMenuCos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCos2ActionPerformed
        funciones = "acos";
        Trigonometria();
    }//GEN-LAST:event_jMenuCos2ActionPerformed

    // Boton que devuelve el valor de la tangente inversa
    private void jMenuTan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTan2ActionPerformed
        funciones = "atan";
        Trigonometria();
    }//GEN-LAST:event_jMenuTan2ActionPerformed
    
    /*
        Trigonometria
        Aqui hay un comparador if que detecta que RadioButton está seleccionado
        para identificar si son radianes o grados los que está recibiendo, 
        dependiendo de lo que esté seleccionado se ejecuta uno u otro codigo
        mediante un switch case.
    */
    public void Trigonometria() {
        if (jRdbSexages.isSelected()) { // si los grados están seleccionados
            switch (funciones) { // elige uno u otro caso
                // Evalua el seno 
                case "sin":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("sin(" + valor1 + ")");
                    sin = Math.sin(Math.PI*(valor1)/180);
                    jTxtPrincipal.setText(sin + " ");
                    break;
                // Evalua el seno inverso
                case "asin":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("sin(" + valor1 + ")");
                    asin = Math.asin((valor1)*180/Math.PI);
                    jTxtPrincipal.setText(asin + " ");
                    break;
                    // Evalua el coseno
                case "cos":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("cos(" + valor1 + ")");
                    cos = Math.cos(Math.PI*(valor1)/180);
                    jTxtPrincipal.setText(cos + " ");
                    break;
                // Evalua el coseno inverso
                case "acos":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("acos(" + valor1 + ")");
                    acos = Math.acos((valor1)*180/Math.PI);
                    jTxtPrincipal.setText(acos + " ");
                    break;
                    // Evalua la tangente
                case "tan":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("tan(" + valor1 + ")");
                    tan = Math.tan(Math.PI*(valor1)/180);
                    jTxtPrincipal.setText(tan + " ");
                    break;
                // Evalua la tangente inversa
                case "atan":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("atan(" + valor1 + ")");
                    atan = Math.atan((valor1)*180/Math.PI);
                    jTxtPrincipal.setText(atan + " ");
                    break;
            }
        } else {
           if (jRdbRadianes.isSelected()) { // si los radianes están seleccionados
            switch (funciones) { // ejecuta uno u otro caso
                // Evalua el seno
                case "sin":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("sinr(" + valor1 + ")");
                    sin = Math.sin(valor1);
                    jTxtPrincipal.setText(sin + " ");
                    break;
                // Evalua el seno inverso
                case "asin":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("sinr(" + valor1 + ")");
                    asin = Math.asin(valor1);
                    jTxtPrincipal.setText(asin + " ");
                    break;
                    // Evalua el coseno
                case "cos":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("cosr(" + valor1 + ")");
                    cos = Math.cos(valor1);
                    jTxtPrincipal.setText(cos + " ");
                    break;
                // Evalua el coseno inverso
                case "acos":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("acosr(" + valor1 + ")");
                    acos = Math.acos(valor1);
                    jTxtPrincipal.setText(acos + " ");
                    break;
                    // Evalua la tangente
                case "tan":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("tanr(" + valor1 + ")");
                    tan = Math.tan(valor1);
                    jTxtPrincipal.setText(tan + " ");
                    break;
                // Evalua la tangente inversa
                case "atan":
                    valor1 = Double.parseDouble(jTxtPrincipal.getText());
                    jTxtSecundario.setText("atanr(" + valor1 + ")");
                    atan = Math.atan(valor1);
                    jTxtPrincipal.setText(atan + " ");
                    break;
            }
        } 
        }
    }
    //</editor-fold>
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Import FlatLaf for custom themes
        try {
            // Setting the dark theme as main
            FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            // Throw error if FlatLaf initialization failed
            System.err.println("Failed to initialize LaF");
        }

        // Putting the rounded buttons, using UIManager
        UIManager.put("Button.arc", 999);

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jFrameCalculator1().setVisible(true);
        });
    }

    public void addNumber(String digito) {
        jLabel1.setText(jLabel1.getText() + digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JPanel Results;
    private javax.swing.JToggleButton ToggleFuntions;
    private javax.swing.JToggleButton ToggleTheme;
    private javax.swing.ButtonGroup Trigonometria;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn17;
    private javax.swing.JButton jBtn19;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAC;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDividedBy1;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEqual;
    private javax.swing.JButton jBtnFactorial;
    private javax.swing.JButton jBtnLn1;
    private javax.swing.JButton jBtnLn2;
    private javax.swing.JButton jBtnMulti;
    private javax.swing.JButton jBtnPi;
    private javax.swing.JButton jBtnResta;
    private javax.swing.JButton jBtnRoundBracket1;
    private javax.swing.JButton jBtnRoundBracket2;
    private javax.swing.JButton jBtnSqrt;
    private javax.swing.JButton jBtnSuma;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblTrigonometria;
    private javax.swing.JMenuItem jMenuCos;
    private javax.swing.JMenuItem jMenuCos2;
    private javax.swing.JMenuItem jMenuSin;
    private javax.swing.JMenuItem jMenuSin2;
    private javax.swing.JMenuItem jMenuTan;
    private javax.swing.JMenuItem jMenuTan2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRdbRadianes;
    private javax.swing.JRadioButton jRdbSexages;
    private javax.swing.JTextField jTxtPrincipal;
    private javax.swing.JTextField jTxtSecundario;
    // End of variables declaration//GEN-END:variables
}
